#This will compare the hashes that you download from the internet and the one generated by you to ensure the hashes matches without human error

$FilePath = read-host -prompt "What is the full file path?"
$FilePath = $FilePath.Trim([char]0x0022)
$OriginalHash = read-host -prompt "What is the hash provided?"
$OriginalHash = $OriginalHash.Trim()

switch ($OriginalHash.length){
    32 {$HashAlgorithm = "md5"}
    40 {$HashAlgorithm = "sha1"}
    64 {$HashAlgorithm = "sha256"}
    128 {$HashAlgorithm = "sha512"}
    default {Write-host -ForegroundColor red "NOT A VALID HASH! EXITING!";exit}
}

$MyHash = get-filehash -algorithm $HashAlgorithm $FilePath

write-host "Vendor hash is: $OriginalHash"
write-host "Your hash is:" $MyHash.Hash

if($OriginalHash -eq $MyHash.Hash) {
    Write-Host "Match" -BackgroundColor black -ForegroundColor Cyan
} else {
    write-host "No Match" -BackgroundColor black -ForegroundColor Red
}
write-host "Algorithm used: $HashAlgorithm"
